In [7]:
#import the required libraries
import numpy as np

#Create a numpy array
array=np.array([1,2,3,4,5],dtype=int)

#numpy array operations
print(array.any())
print(array.all())
print(np.isnan(array).any())
print(np.isinf(array).any())
print(np.isfinite(array).all())
print(np.zeros(array))
print(np.isreal(array).all())
print(np.iscomplex(array).all())
print(np.isscalar(array))
print(np.less(array,3))
print(np.greater(array,3))
print(np.less_equal(array,3))
print(np.greater_equal(array,3))

#create an array using linspace() or arrange()
array1=np.arange(1,5,1)#Adjusted 4 elements

#Reshape the array
array1=array1.reshape(2,2)

# use randint() to create an array of random integers
array2 = np.random.randint(1, 10, 4).reshape(2, 2)  # Reshape to (2, 2)

#matrix multiplication
result=np.dot(array1,array2)
print(result)




True
True
False
False
True
[[[[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]


  [[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]]]
True
False
False
[ True  True False False False]
[False False False  True  True]
[ True  True  True False False]
[False False  True  True  True]
[[23  7]
 [55 19]]
